name: Fullstack Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 sync ./dist s3://trivia-app422025-bucket --delete

      - name: Init Terraform with backend config
        env:
          TF_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
          TF_STATE_KEY: ${{ secrets.TF_STATE_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          terraform init \
            -backend-config="bucket=$TF_STATE_BUCKET_NAME" \
            -backend-config="key=$TF_STATE_KEY" \
            -backend-config="region=$AWS_REGION"

      - name: Apply Terraform
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve

      - name: Get CloudFront Distribution ID from Terraform
        run: |
          echo "CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
